version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # - aws cloudfront create-invalidation --distribution-id E1T1W9UP53PVQ1 --paths "/*"
      # copy the contents of /build to S3
artifacts:
  files:
    - "**/*"
  base-directory: build
