import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../store";
import { handleLogin, loginAction, loginFailed } from "./actions/authActions";

export interface AuthState {
  user?: any;
  status: "idle" | "loading" | "failed" | "passwordResetRequired" | "PasswordResetSuccessfull";
  resetEmail?: string;
  authError?: string;
  token?: string;
  payLoadValues: any;
}

const initialState: AuthState = {
  status: "idle",
  payLoadValues: null,
};

export const authSlice = createSlice({
  name: "auth",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    resetErrorAction: (state) => {
      delete state.authError;
    },
    setPayloadValues: (state: any, value) => {
      state.payLoadValues = value.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loginAction.pending, (state) => {
        state.status = "loading";
        delete state.authError;
      })
      .addCase(loginAction.fulfilled, handleLogin)
      .addCase(loginAction.rejected, loginFailed);
  },
});

export const { resetErrorAction, setPayloadValues } = authSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectStatus = (state: RootState) => state.auth.status;
export const selectAuthError = (state: RootState) => state.auth.authError;
export const selectUser = (state: RootState) => state.auth.user;
export const isLogin = (state: RootState) => {
  return Boolean(state.auth.user?.Username);
};
export const payLoadValues = (state: RootState) => state.auth.payLoadValues;
